# Python Sandbox (Notes)

### stdin & stdout
These Python commands read files from the system and output. 


In [ ]:
import sys

count = 0 #this will count the # of lines in an input
for line in sys.stdin:
    count+=1
    
print(count)

######################
#you would save the below as 'most_common_words.py'
from collections import Counter

try: #this will find the number of words in a given input
    num_words = int(sys.argv[1]) #index pos 0 is the name of the program itself
except:
    print("usage: most_common_words.py num_words")
    sys.exit(1) #nonzero exit code indicates an error has occured

counter = Counter(word.lower() 
                  for line in sys.stdin
                  for word in line.strip().split() #splits on spaces if no char is passed
                  if word) #evaluates false for empty words

for word, count in counter.most_common(num_words):
    sys.stdout.write(str(count))
    sys.stdout.write("\t")
    sys.stdout.write(word)
    sys.stdout.write("\n")
    
#To run this, would you need to execute

$ cat sometextfile.txt | python most_common_words.py #this is for UNIX based. 
#The output of LEFT is run by RIGHT of pipe


### Open/Close Files in System

In [ ]:
filetoread = open('read_this_file.txt', 'r')
# r = read-only, this is default
# w = write, this will destroy the file if it already exists
# a = append, this will add to the end of the file 

filetoread.close() # this will close the file when you're all done
#This way the file will be closed after the block completes. 
#You can get around having to open/close files by using a 'with' block:

with open(filename) as f:
    data = function_that_pulls_stuff_from_file(f)
    func_that_does_stuff(data)
#you can iterate through line by line if you have to read the entire file.

def process(date: str, symbol: str, closing_price: float) -> None:
    # Imagine that this function actually does something.
    assert closing_price > 0.0

import csv

with open('tab_delimited_stock_prices.txt') as f:
    tab_reader = csv.reader(f, delimiter='\t')
    for row in tab_reader:
        date = row[0]
        symbol = row[1]
        closing_price = float(row[2])
        process(date, symbol, closing_price)
        
        csv_writer = csv.writer(f, delimiter=',')
        todays_prices = {'AAPL': 90.91, 'MSFT': 41.68, 'FB': 64.5 }
        for stock, price in todays_prices.items():
            csv_writer.writerow([stock,price])

### Web-scraping and Parsing Web data
Requests, BeautifulSoup, HTML, XML, JSON

In [ ]:
#As a note. The Python built-in HTML library is not very lenient so it will do poorly with bad HTML. 
#We'll use html5lib instead.

from bs4 import BeautifulSoup
import requests

url = ("https://raw.githubusercontent.com/"
       "joelgrus/data/master/getting-data.html")
html = requests.get(url).text
soup = BeautifulSoup(html, 'html5lib')

soup.find('p') 
soup.p #these will do the same thing. Find all the p tags in the soup object.

all_paragraphs = soup.find_all('p')  # or just soup('p')
paragraphs_with_ids = [p for p in soup('p') if p.get('id')]

important_paragraphs = soup('p', {'class' : 'important'})
important_paragraphs2 = soup('p', 'important')
important_paragraphs3 = [p for p in soup('p')
                         if 'important' in p.get('class', [])]



### Itertools
This package makes it easier to make iterable sequences...

In [9]:
import itertools
friends = ['Team 1', 'Team 2', 'Team 3', 'Team 4'] #You want to create different permutations of this list 
list(itertools.combinations(friends, r=2))

#itertools also has the itertools.permutations() method to do the same thing

[('Team 1', 'Team 2'),
 ('Team 1', 'Team 3'),
 ('Team 1', 'Team 4'),
 ('Team 2', 'Team 3'),
 ('Team 2', 'Team 4'),
 ('Team 3', 'Team 4')]

### Regex + F-Strings

In [2]:
import re

print("Output:") 
for char in [r"*", r"%", r"+", r"-"]:
    
    regex = re.compile(fr"The character {char} is an operator in Python.")
    print(regex, type(regex))
    #we can add some

Output:
re.compile('The character * is an operator in Python.') <class '_sre.SRE_Pattern'>
re.compile('The character % is an operator in Python.') <class '_sre.SRE_Pattern'>
re.compile('The character + is an operator in Python.') <class '_sre.SRE_Pattern'>
re.compile('The character - is an operator in Python.') <class '_sre.SRE_Pattern'>


### Enumerate() method
This will add a COUNTER to an ITERABLE object and return it as a enumerate object.

In [7]:
numbers = [30, 42, 28, 50, 15]
for i, num in enumerate(numbers):
    if num % 3 == 0 and num % 5 == 0:
       numbers[i] = 'threefive'
    elif num % 3 == 0:
       numbers[i] = 'three'
    elif num % 5 == 0:
       numbers[i] = 'five'
print(numbers)

['threefive', 'three', 28, 'five', 'threefive']


### NumPy

In [6]:
import numpy as np

In [7]:
rarray = np.random.rand(6,6)

In [8]:
print(rarray)

[[0.71743307 0.95371141 0.81364319 0.60878408 0.18221915 0.13449025]
 [0.59443827 0.31458399 0.00402874 0.78887061 0.03399027 0.55736257]
 [0.50030285 0.0437602  0.44170829 0.83167229 0.97863304 0.17551678]
 [0.10949048 0.57531763 0.91656336 0.67338377 0.73858747 0.51459732]
 [0.27353444 0.24531603 0.29277674 0.12995186 0.09672717 0.61248456]
 [0.63644249 0.06639662 0.54602959 0.62894861 0.77155117 0.55054817]]


In [10]:
np.sort(rarray, axis=1, kind = 'quicksort')

array([[0.13449025, 0.18221915, 0.60878408, 0.71743307, 0.81364319,
        0.95371141],
       [0.00402874, 0.03399027, 0.31458399, 0.55736257, 0.59443827,
        0.78887061],
       [0.0437602 , 0.17551678, 0.44170829, 0.50030285, 0.83167229,
        0.97863304],
       [0.10949048, 0.51459732, 0.57531763, 0.67338377, 0.73858747,
        0.91656336],
       [0.09672717, 0.12995186, 0.24531603, 0.27353444, 0.29277674,
        0.61248456],
       [0.06639662, 0.54602959, 0.55054817, 0.62894861, 0.63644249,
        0.77155117]])

In [ ]:
print(rarray) #looks like this ordered the array row-by-row

In [12]:
grades = np.array([1, 3, 4, 2, 5, 5, 6, 1, 2])

##### np.where()

In [13]:
np.where(grades > 3)
#this will grab any INDICES of VALUES that satisfy the conditional statement
#you can go further with this method by passing in replacements...
#syntax -> np.where(conditional, replace true, replace false)

(array([2, 4, 5, 6], dtype=int64),)

In [14]:
np.where(grades > 3, 'passing', 'failing')

array(['failing', 'failing', 'passing', 'failing', 'passing', 'passing',
       'passing', 'failing', 'failing'], dtype='<U7')

##### argmin / max / sort()

In [18]:
#argmin -> Returns index of minima
#argmax -> Returns index of maxima
#sort -> Returns sorted index 
display(grades)
display(grades.argmin()) 
display(grades.argmax())
display(grades.argsort())

array([1, 3, 4, 2, 5, 5, 6, 1, 2])

0

6

array([0, 7, 3, 8, 1, 2, 4, 5, 6], dtype=int64)

In [28]:
grades2 = np.array(np.random.randint(1,10,9))
print(grades2)

np.intersect1d(grades, grades2)

[6 4 3 7 2 8 2 6 2]


array([2, 3, 4, 6])

### Pandas

### Python Packages

#### Emoji Package

In [ ]:
pip install emoji

from emoji import emojize
print(emojize(":thumbs_up:")) 

### Engineering Principles

#### List Comprehensions


In [ ]:
numbers = [1,2,3,4,5,6,7]
evens = [x for x in numbers if x % 2 is 0]
odds = [y for y in numbers if y not in evens]
cities = ['London', 'Dublin', 'Oslo']
def visit(city):
    print("Welcome to "+city)
for city in cities:
    visit(city)

### Python Snippets

In [ ]:
def split_lines(s): #split a string into pieces using a separator
  return s.split('\n')
split_lines('50\n python\n snippets')

################################################################
language = "python" #reverse the order of the letters in a word                                 
reversed_language = language[::-1]
print(reversed_language)


################################################################
def union(a,b): #find elements that exist in both lists
  return list(set(a + b))
union([1, 2, 3, 4, 5], [6, 2, 8, 1, 4])

################################################################
def unique(list): #finds if all elements in a list are unique
    if len(list)==len(set(list)):
        print("All elements are unique")
    else:
        print("List has duplicates")
unique([1,2,3,4,5]) # All elements are unique

################################################################
from collections import Counter #counts freq of appearance of elements
list = [1, 2, 3, 2, 4, 3, 2, 3]
count = Counter(list)
print(count) # {2: 3, 3: 3, 1: 1, 4: 1}

################################################################
def most_frequent(list): #piggy-backing, finds most freq appearance of elements
    return max(set(list), key = list.count)
numbers = [1, 2, 3, 2, 4, 3, 1, 3]
most_frequent(numbers) # 3

################################################################
def multiply(n): #mapping applies the function in the parens to the data element in the parens
    return n * n 

list = (1, 2, 3) 
result = map(multiply, list) 
print(list(result)) # {1, 4, 9)

################################################################
### Lambda Syntax:   
X = lambda a, b : a * b
Lambda (variables, any number) : function to perform using said variables
    
################################################################
### Mapping and Filtering
Maps: applies a function to the data provided it.
X = map(func name, data to get func’d)

Filters: Same thing as mapping, but only returns True evaluations.
X = filter(func, data to get func’d)

 
##################################################################
###The Itertools Library:
#Izip function - this will take 2 lists and create a new tuple with each element of the list.
[a, b, c] + [1, 2, 3] + izip = (a, 1) (b, 1) (c, 1)

You can recreate similar using the ‘count’ function and passing in a 1:
For i in izip(count(1), [‘Bob’, ‘Emily’, ‘Joe’]):
Print(i)

#Dropwhile() function - will return values that follow a condition AFTER the condition results in ‘False’ the first time

For X in dropwhile(drop_check, [2 ,4 ,6 ,8, 10, 12]):
Print ('Result: X)

Drop_check function in this example evaluates x > 5
The return for this function would only print 6, 8, 10, and 12.

##################################################################
#Flask Hello World:

From flask import Flask <- this is the main directory for the flask framework

App = Flask(__name__) <- this initializes and then gives the flask object ‘app’ as a name

@app.route(‘/’) <- for the ‘app’ object, we route the URL of / (usually a home page or something) to the home function defined below.

Def home():
          Return “<h1> Hello World </h1>”