# Python Sandbox (Notes)

### NumPy

In [6]:
import numpy as np

In [7]:
rarray = np.random.rand(6,6)

In [8]:
print(rarray)

[[0.71743307 0.95371141 0.81364319 0.60878408 0.18221915 0.13449025]
 [0.59443827 0.31458399 0.00402874 0.78887061 0.03399027 0.55736257]
 [0.50030285 0.0437602  0.44170829 0.83167229 0.97863304 0.17551678]
 [0.10949048 0.57531763 0.91656336 0.67338377 0.73858747 0.51459732]
 [0.27353444 0.24531603 0.29277674 0.12995186 0.09672717 0.61248456]
 [0.63644249 0.06639662 0.54602959 0.62894861 0.77155117 0.55054817]]


In [10]:
np.sort(rarray, axis=1, kind = 'quicksort')

array([[0.13449025, 0.18221915, 0.60878408, 0.71743307, 0.81364319,
        0.95371141],
       [0.00402874, 0.03399027, 0.31458399, 0.55736257, 0.59443827,
        0.78887061],
       [0.0437602 , 0.17551678, 0.44170829, 0.50030285, 0.83167229,
        0.97863304],
       [0.10949048, 0.51459732, 0.57531763, 0.67338377, 0.73858747,
        0.91656336],
       [0.09672717, 0.12995186, 0.24531603, 0.27353444, 0.29277674,
        0.61248456],
       [0.06639662, 0.54602959, 0.55054817, 0.62894861, 0.63644249,
        0.77155117]])

In [ ]:
print(rarray) #looks like this ordered the array row-by-row

In [12]:
grades = np.array([1, 3, 4, 2, 5, 5, 6, 1, 2])

##### np.where()

In [13]:
np.where(grades > 3)
#this will grab any INDICES of VALUES that satisfy the conditional statement
#you can go further with this method by passing in replacements...
#syntax -> np.where(conditional, replace true, replace false)

(array([2, 4, 5, 6], dtype=int64),)

In [14]:
np.where(grades > 3, 'passing', 'failing')

array(['failing', 'failing', 'passing', 'failing', 'passing', 'passing',
       'passing', 'failing', 'failing'], dtype='<U7')

##### argmin / max / sort()

In [18]:
#argmin -> Returns index of minima
#argmax -> Returns index of maxima
#sort -> Returns sorted index 
display(grades)
display(grades.argmin()) 
display(grades.argmax())
display(grades.argsort())

array([1, 3, 4, 2, 5, 5, 6, 1, 2])

0

6

array([0, 7, 3, 8, 1, 2, 4, 5, 6], dtype=int64)

In [28]:
grades2 = np.array(np.random.randint(1,10,9))
print(grades2)

np.intersect1d(grades, grades2)

[6 4 3 7 2 8 2 6 2]


array([2, 3, 4, 6])

### Pandas